name: Update Book Gallery

on:
  schedule:
    - cron: '0 7 * * *' # every day at 7:00 UTC
  workflow_dispatch:

jobs:
  update-book-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Fetch book covers and update gallery
        run: python .github/scripts/fetch_books_openlibrary.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: update book gallery [bot]'
          file_pattern: 'glance-resume-splash/public/books_openlibrary.json'
